version: '3'
services:
  api:
    build: ./
    restart: always
    # ports:
    #   - '${APP_DOCKER_PORT}:3000'
    volumes:
      - './:/app'
      - './.data:/app-data'
    networks:
      - lognet
    environment:
      - ACCOUNT_PHONE
      - ACCOUNT_PWD
      # - TF_CPP_MIN_LOG_LEVEL
networks:
  lognet:
    driver: bridge